---
title: "Parte 1: Diversidad"
author: "Gabriel Massaine Moulatlet"
date: "2022-09-02"
output: html_document
---

#### Parte 1
##### Diversidad y Riqueza

Cargar los siguientes paquetes:
```{r eval=F}
library(vegan)
library(vegetarian)
library(plyr)
library(directlabels)
library(viridis)
library(ggplot2)
```

Usar los numeros de Hill en los analisis de diversidad
comunidade con especies de misma abundancia
```{r eval=FALSE}
# crear una comunidad donde todas las especies tienen la misma abundancia
co = as.data.frame(matrix(NA, nrow=1,ncol=3))
co[1,] =c(6,6,6)
colnames(co) =c("birch","pine","spruce")
co

# cual es la riqueza?
specnumber(co)

# cual es la abundancia proporcional de cada especie?

co[1,1]/rowSums(co)
co[1,2]/rowSums(co)
co[1,3]/rowSums(co)

# en este caso, la abundancia proporcional es 1/R
```

Comunidade con especies de abundancias diferentes
```{r eval=FALSE}
# crear una comunidad donde todas las especies tienen diferentes abundancias
co2 = as.data.frame(matrix(NA, nrow=1,ncol=3))
co2[1,] =c(4,2,12)
colnames(co2) =c("birch","pine","spruce")

# cual es la abundancia proporcional de cada especie?
co2[1,1]/rowSums(co2)
co2[1,2]/rowSums(co2)
co2[1,3]/rowSums(co2)

#en este caso la diversidad es 1/suma del promedio de las abundancias relativas
```

```{r eval=FALSE}

# cual es la diversidad de la co2?
# calcular las medias y comparar con los valores q

# media armonica
1/(1/sum(c(0.2222/0.2222, 0.11111/0.1111,0.666667/0.66667)))
d(co2,q=0)

# media geometrica
1/(0.2222^0.2222 *0.11111^0.1111*0.666667^0.66667)
d(co2,q = 1)

# media aritimetica
1/sum(0.2222*0.2222, 0.11111*0.1111, 0.666667*0.66667)
d(co2,q = 2)

# si hay interes pueden rehacer los calculos de la diapositiva 21
18/(1/0.3333334)
18/(1/(0.2222^0.2222 *0.11111^0.1111*0.666667^0.66667))
18/(1/sum(0.2222*0.2222, 0.11111*0.1111, 0.666667*0.66667))
```

Comparar los indices de Shannon y Simpson con los numeros de Hill y hacer la conversion
```{r eval=FALSE}
#indice de Shannon
exp(diversity(co2,index = "shannon"))
d(co2,q=1)

#indice de Simpson
diversity(co2,index = "invsimpson")
d(co2,q=2)

#Los resultados de los indices son similares a los de los numeros de Hill?
```

Particionar la diversidad
```{r eval=FALSE}
# partitioning diversity #########
#Primer hay que crear una comunidad con tres unidades de composicion y tres spp.

co3 = as.data.frame(matrix(NA, nrow = 3, ncol = 3))
colnames(co3) = c("sp1","sp2","sp3")
rownames(co3) = c("su1","su2","su3")

co3[1,] = c(5,1,0)
co3[2,] = c(3,3,0)
co3[3,] = c(4,0,2)

# calcular el gamma, alpha y beta richness
d(co3,q=0,lev = "gamma")
d(co3,q=0,lev = "alpha")
d(co3,q=0,lev = "beta")

# calcular el gamma, alpha y beta diversity at q=1
d(co3,q=1,lev = "gamma")
d(co3,q=1,lev = "alpha")
d(co3,q=1,lev = "beta")

```

```{r eval=FALSE}
#### graficar la diversidad de la comunindad 3 ####

#el looping abajo calcula la diversidad usando media generalizada
com <- co3
h <- c(0,0.5,1,1.5,2,3,5) # definir los valores q
hilldf <- list(NA)
hillq <- matrix(NA,nrow = 7,ncol=4)
hillq[,2]<- h

for(i in seq(nrow(com))){
  
  com2 <- com[i,]
  com3 <- decostand(com2[,which(com2>0)], method = "total", MARGIN = 1)
  
  for(q in unique(h)){
    
    if(q!=1){d <- (sum(com3^q))^(1/(1-q))
    }else {d <- exp(diversity(com3))}
    
    hillq[which(h==q),1] <-d
    hillq[,3] <- rownames(com3)
    
    e <- d/(sum(com3^0))^(1/(1-0))
    hillq[which(h==q),4] <-e
    
    hilldf[[i]] <- hillq
  }
}

div <- ldply(hilldf,data.frame)
colnames(div) <- c("diversity","q","ID", "eveness")

div[,1] <- as.numeric(div[,1])
div[,1] <- round(div[,1],3)
div[,2] <- as.numeric(div[,2])
div[,3] <- as.factor(div[,3])
div[,4] <- as.numeric(div[,4])
div[,4] <- round(div[,4],3)


# grafico diversidad

g1 <-ggplot(div,aes(x=q,y=diversity,group=ID,color=ID))+
  geom_line(size=0.8)+
  geom_dl(aes(label=ID), method=list(dl.trans(x = x + 0),"first.bumpup",cex=1))+
  theme_bw()+
  scale_x_continuous(limits = c(-1, 5),breaks = c(0,1,2,3,4,5))+
  theme(axis.title = element_text(size = 20))+
  theme(text = element_text(size=20))+
  theme(axis.text = element_text(color = "black"),panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())+
  ylab("Diversity")+
  scale_color_viridis(discrete = TRUE)+
  theme(legend.position = "none")
g1
```

Alpha, Beta, Gamma
```{r eval=FALSE}
# particionamiento de la diversidad ###
#gamma= alpha*beta

h <- c(0,0.5,1,1.5,2,3,5)
gamma <- as.data.frame(matrix(nrow = 7,ncol = 4))
colnames(gamma) <- c("a","b","g","q")

for(i in unique(h)){
  if(i==0)  {j=1}
  if(i==0.5){j=2}
  if(i==1)  {j=3}
  if(i==1.5){j=4}
  if(i==2)  {j=5}
  if(i==3)  {j=6}
  if(i==5)  {j=7}
  
  gamma[j,1] <- d(com,lev = "alpha",wts = FALSE,q=i)
  gamma[j,2] <- d(com,lev = "beta", wts = FALSE,q=i)
  gamma[j,3] <- d(com,lev = "gamma",wts = FALSE,q=i)
  gamma[4] <- h
}

gammaM <- melt(gamma,id=c("q"))
colnames(gammaM)[2] <- "index"

# grafico

g2 <- ggplot(data=gammaM, aes(y=value, x=q, group=index))+
  geom_line(aes(color=index),size=1.5)+
  theme_bw()+
  ylab("Diversity Partitioning")+
  theme(legend.position = c(0,1),legend.justification=c(-1.1,1.1),
        legend.title = element_blank(),
        legend.text = element_text(size=20))+
  theme(axis.title = element_text(size = 20))+
  theme(text = element_text(size=20))+
  theme(axis.text = element_text(color = "black"),panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())+
  scale_color_viridis(discrete = TRUE,labels=c(expression(alpha),expression(beta),expression(gamma)))
g2

```